### ISSUE TITLE
Use Generators to reduce memory usage with big amount of "tasks" in Queue?

### ISSUE THREAD

**Issue by holtkamp** [clue/reactphp-mq#13] opened 2018-05-31 11:42 UTC
Also see https://github.com/dpovshed/octopus/issues/17

In an effort to switch from an ["in-house" Queue implementation](https://github.com/dpovshed/octopus/blob/9dfc15cab7d922c79453eab9ec8d71dd3f2c9d6e/src/Processor.php#L132-L154), I am trying to adopt `reactphp-mq` when crawling the URLs in a Sitemap (Index). This seems to be achievable, the first attempt works: https://github.com/dpovshed/octopus/pull/25 

**Greedy memory usage**
One thing I noticed however, was the big increase in allocated memory. When crawling a Sitemap of ~7500 URLs in https://github.com/dpovshed/octopus using:
- the "in-house" approach of a Queue: around `6M` of memory is used
- the MQ-react approach of a Queue: around `70M` of memory is used

I think this is because the MQ Queue [gets populated with a Promise object for each to-be-crawled URL upon initialization](https://github.com/holtkamp/octopus/blob/0c8b08bc78cfca00ec8d91f3bb7810be1d581335/src/Processor.php#L119-L125), each Promise object requires some memory. The "in-house" approach iterates over the workload "on the go". 

Of course, the slight increase in memory does not have to be a big problem. However, when processing large amounts of task, like a Sitemap with ~100k URLs, this would now consume around `900M` of memory!

So that got me thinking. Not sure whether it is possible, but maybe a [Generator](http://php.net/manual/en/language.generators.overview.php) can be used to `yield` the Promises and instantiate them "on-to-go" when the Queue is being processed instead of all-at-once upon initialization of the Queue?

Is seems that having the Queue using a [LazyPromise](https://reactphp.org/promise/#lazypromise) would require the same amount of memory per Promise...

Maybe I am suggesting crazy things, the whole asynchronous processing and use of Promises is quite new to me 😄

**Comment by clue** [comment] 2018-06-02 18:53
That's an interesting issue! :+1: 

This project was indeed designed to handle dozens or hundreds of operations and keeps all operations in memory by design. This means that there's a limit in how many operations can be queued at once (which is why there's a maximum $limit option).

If you want to process hundreds or thousands operations, you may want to use https://github.com/clue/reactphp-flux instead. This is a project I've started working on after building this one and that one is particularly designed for a streaming approach for a large number of operations.

I'm not opposed to the idea of using a Generator-based approach here, but I'm currently unsure how much this would actually help. Maybe you can give Flux a try first and see how this works out for your use case?

I hope this helps! :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2018-06-02 18:53 UTC
Labels: new feature, question

**Comment by holtkamp** [comment] 2018-06-12 08:57
FYI: started experimenting with https://github.com/clue/reactphp-flux to realize this, the results are promising, ~100k URLs now only takes `16M`

I created a SitemapLoader that provides the stream to the transformer. Since we need the entire Sitemap content, we need to wait until all data is loaded before processing the Sitemap. 

Some improvements are still possible, for example: a Sitemap Index contains links to other Sitemaps. These are now loaded using `file_get_contents()`, but a stream can be used for this as well, resulting in a recursive stream? Not sure whether this is a good idea 😄 

https://github.com/holtkamp/octopus/tree/use-react-flux

https://github.com/holtkamp/octopus/blob/10f35564396522a1cf5f12666b1bb218d0fbffc5/src/Sitemap/Loader.php

**Comment by clue** [comment] 2018-06-12 10:16
Thank you for posting back and sharing these interesting numbers! I'm happy to hear this seems to be working out really well! :+1: 

The linked `Loader` basically buffers the whole sitemap contents into memory and then invokes an XML parser on it, so this actually be simplified somewhat by using https://github.com/reactphp/promise-stream#buffer like this:

```
Stream\buffer($input)->then(function ($contents) use ($transformer) {
    $all = parse($contents);
    foreach ($all as $one) {
        $transformer->write($one);
    }
});
```

This is all asynchronous, so you may also use this concurrency when fetching multiple sitemaps (by following links to other sitemaps).

This should work just fine as long as your sitemap is small enough to fit into memory at once. Once this starts becoming an issue, you may want to use a streaming approach instead and use a streaming XML parser (SAX).

**Comment by holtkamp** [comment] 2018-06-12 11:12
Thanks for the great pointers. Yeah I was thinking of using https://github.com/clue/reactphp-buzz to load any Sitemaps that are encountered will processing a Sitemap Index, but got stuck...

When using _the same loop_, it seems the "URLs that were added to the stream asynchronously", are emitted properly, but the transformer does not actually process/transform them.... Is if it were they are not piped through properly / receive them...

I tried this:

```php
    private function processSitemapUrlAsynchronously(string $sitemapUrl): void
    {
        $client = new Browser($this->loop); //Re-use the "main" loop

        $client->get($sitemapUrl)->then(function (ResponseInterface $response) {
            $data = (string)$response->getBody();
            if ($sitemapElement = $this->getSimpleXMLElement($data)) {
                $this->processSitemapElement($sitemapElement);
            }
        });
    }
```

It _does work_ when using _a new loop_:

```php
    private function processSitemapUrlAsynchronously(string $sitemapUrl): void
    {
        $loop = \React\EventLoop\Factory::create(); //Use a new loop (nested? Is this ok to do?)
        $client = new Browser($loop);

        $client->get($sitemapUrl)->then(function (ResponseInterface $response) {
            $data = (string)$response->getBody();
            if ($sitemapElement = $this->getSimpleXMLElement($data)) {
                $this->processSitemapElement($sitemapElement);
            }
        });

        $loop->run()
    }
```

However I am not sure whether using such new loop is "ok" to do. When a lot if Sitemaps are encountered, this would mean a lot of loops. So I guess I got some reading to do to understand what the best approach would be.

Offtopic: Very interesting and powerful mechanisms, but sometimes difficult to grasp how it works exactly as well 😉

**Comment by holtkamp** [comment] 2018-06-12 11:20
>so this actually be simplified somewhat by using XYZ

So you mean not using a stream with `fopen()` at all and only use Transformers and chain/pipe them?

Something like this:
- one Transformer to load the Sitemaps and collect the URLs
- one Transformer to crawl the collected URLs

```php
$transformerThatCollectsUrlsFromSitemaps->pipe($transformerThatCrawlsUrls);
```

**Comment by clue** [comment] 2018-06-12 13:52
> Offtopic: Very interesting and powerful mechanisms, but sometimes difficult to grasp how it works exactly as well :wink: 

Absolutely! There's no denying the fact that this takes some time to get used to. But IMHO it's very well worth it :+1: 

> When using the same loop, it seems the "URLs that were added to the stream asynchronously", are emitted properly, but the transformer does not actually process/transform them.... Is if it were they are not piped through properly / receive them...

Not sure how much I can help here, but as a rule of thumb a truly asynchronous program should only ever use a single event loop and only have a single `run()` call at the very end.

>> so this actually be simplified somewhat by using XYZ

> So you mean not using a stream with fopen() at all and only use Transformers and chain/pipe them?

Again, this is difficult to answer without having a better understanding of your particular problem. A `Transformer` is designed to act as an intermediary within a pipe of streams ("transform from input stream A to output stream B"). In your particular case, your input does not appear to be streaming at all, so not much would be gained by applying this through another transformer.

If it ain't broken, don't fix it? :shipit:

**Comment by holtkamp** [comment] 2018-06-12 14:41
ok, thanks a bunch, will monitor your projects with interest!
