### ISSUE TITLE
Add a way to increase queue concurrency

### ISSUE THREAD

**Issue by OpenSource03** [clue/reactphp-mq#40] opened 2023-05-30 09:59 UTC
Hi! Would it be possible to add a way to increase the queue concurrency dynamically via setConcurrency for example?

**Comment by clue** [comment] 2023-05-30 11:52
@OpenSource03 Thank you for bringing this up, this looks like a duplicate of #20, so I'll close this one.

**Closed as not planned by clue** 2023-05-30 11:52 UTC
Labels: new feature
